name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: Build Fat Library
        run: sh build-fat.sh

      - name: Build Binding Library
        run: msbuild Xamarin.Nuke/Xamarin.Nuke.sln /p:Configuration=Release

      - name: Create NuGet Package
        run: nuget pack -Version ${{ steps.gitversion.outputs.nuGetVersionV2 }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: NuGet
          path: '*.nupkg'
