name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
   
      - name: Install Workloads
        run: dotnet workload install ios maccatalyst

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: Build NukeProxy Native Library
        run: sh build.sh

      - name: Build Binding Legacy Library
        run: msbuild Xamarin.Nuke/Xamarin.Nuke/Xamarin.Nuke.csproj /p:Configuration=Release

      - name: Build Binding NET6 Library
        run: dotnet build Xamarin.Nuke/Xamarin.Nuke.NET6/Xamarin.Nuke.NET6.csproj /p:Configuration=Release

      - run: |
          sed -i.bak "s|%branch%|$BRANCH|g" Xamarin.Nuke.nuspec
          sed -i.bak "s|%commit%|$SHA|g" Xamarin.Nuke.nuspec
        name: Patch nuspec
        env:
          BRANCH: ${{ github.ref }}
          SHA: ${{ github.sha }}

      - name: Create NuGet Package
        run: nuget pack -Version ${{ steps.gitversion.outputs.nuGetVersionV2 }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: NuGet
          path: '*.nupkg'
